#!/usr/bin/env python3

import asyncio
import cProfile
import pstats
import select
import json
import argparse
import datetime
from typing import Optional

from bpdu import BPDU
from port import Port, PortStatus


# accepts an error param and prints a debug log
def error_log(error: str):
    print(f"[ERROR] {error}")


# This object represents a bridge, It is responsible for building the minimum spanning tree.

class Bridge:
    ports: list[Port]

    # init bridge object with data for first BPDU. At the start, bridge believes it is the root
    # and cost to root is 0 and all ports are enabled
    def __init__(self, ports: list, bridge_id: str, socket_to_port: dict, port_id_to_portObj: dict):
        """
        This class represents a bridge and handles all logic for building a forwarding table and executing the
        spanning tree algorithm
        :param ports: List of Port objects
        :param bridge_id: ID of this bridge
        """
        # list of all ports on this bridge
        self.ports = ports
        self.bridge_id = bridge_id
        self.root = bridge_id
        self.root_cost = 0
        self.socket_to_port = socket_to_port
        # dictionary that maps each destination to port object
        self.forwarding_table = {}
        # this maps a port id to the object of class Port
        self.port_id_to_portObj = port_id_to_portObj
        # keeps track of the time when the last BPDU was sent from this bridge
        self.last_bpdu_sent = datetime.datetime.now()
        # interval to send BPDU
        self.bpdu_interval = 0.45

    # returns a serialized BPDU for this bridge from the port given as the argument
    def get_bpdu(self, port_sent_from: int) -> BPDU:
        return BPDU(self.root, self.root_cost, self.bridge_id, port_sent_from)

    def update_designated_port_status(self):
        """
        Update ports as designated port if they are not the root port and their best BPDU is better than all
        the BPDUs heard by them
        Disables all non designated and non-root ports
        :return: None
        """
        for port in self.ports:
            if port.status == PortStatus.ROOT:
                continue
            bridge_best_bpdu = self.get_bpdu(port.id)
            port_best_bpdu = port.get_best_bpdu()
            # a port is disabled if it has heard a BPDU and if it is worse than the bridges best one
            if port.has_received_bpdu() and bridge_best_bpdu > port_best_bpdu:
                port.status = PortStatus.DISABLED
                print(f"Disabled port {port.id}", flush=True)
            else:
                port.status = PortStatus.DESIGNATED
                print(f"Designated port {port.id}", flush=True)

    # resets forwarding table
    def flush_table(self):
        self.forwarding_table = {}

    def update(self, bpdu: dict, port_id: int):
        """
        :param bpdu: The BPDU that was received in JSON format
        :param port_id: The 0-indexed id of the port that the message was heard on
        :return: None

        This method performs the logic required to reconfigure the spanning tree when a new BPDU is heard.
        The method also takes care of filtering out the cases where no update is needed to the root or root port on the bridge

        """
        port_received_on = self.port_id_to_portObj[port_id]
        flush_table = port_received_on.try_to_add_new_bpdu(bpdu["message"])
        send_bpdus = False
        if flush_table:
            self.flush_table()
            send_bpdus = True
        best_bpdu_received, port_heard_on = self.best_bpdu_over_all()
        if best_bpdu_received:
            if best_bpdu_received > self.get_bpdu(0):
                print("Root port: None", flush=True)
            else:
                if best_bpdu_received.root != self.bridge_id:
                    # rebroadcast BPDU if better root is found or better path to same root is found
                    if best_bpdu_received.root != self.root or (best_bpdu_received.root == self.root and
                                                                best_bpdu_received.cost + 1 < self.root_cost):
                        send_bpdus = True
                    self.update_root_port(best_bpdu_received, port_heard_on)
            self.update_designated_port_status()
            if send_bpdus or self.bpdu_interval_expired():
                self.send_bpdus()
        else:
            self.set_all_ports_as_designated()
            self.root = self.bridge_id
            self.root_cost = 0
            self.send_bpdus()

    def bpdu_interval_expired(self) -> bool:
        """
        Checks if the bridges BPDU hasn't been sent for longer than the preset interval
        :return: True if BPDU needs to be sent, False otherwise
        """
        return (datetime.datetime.now() - self.last_bpdu_sent).total_seconds() > self.bpdu_interval

    # sets all ports as designated ports
    def set_all_ports_as_designated(self):
        for port in self.ports:
            port.status = PortStatus.DESIGNATED

    def best_bpdu_over_all(self) -> Optional[tuple[BPDU, int]]:
        """
        returns the best bpdu that this bridge has heard and the port it was heard on. Returns None if no BPDU has been
        heard
        :return: (BPDU, int) if a best BPDU exists or None
        """
        best_bpdu = None
        port_heard_on = None
        for port in self.ports:
            port.clean_bpdus()
            if not port.has_received_bpdu():
                continue
            port_best_bpdu = port.get_best_bpdu()
            if best_bpdu is None or port_best_bpdu < best_bpdu:
                best_bpdu = port_best_bpdu
                port_heard_on = port.id
        return best_bpdu, port_heard_on

    def get_tasks(self):
        """
        Returns a list of port.send_bpdu() tasks
        :return: list of tasks
        """
        tasks = []
        for port in self.ports:
            tasks.append(port.send_bpdu(self.get_bpdu(port.id).serialize()))
        return tasks

    # This method sends a BPDU on all ports.  You might want to call this regularly...
    def send_bpdus(self):
        """Async function to send bpdu"""
        start = datetime.datetime.now()
        # tasks = self.get_tasks()
        # await asyncio.gather(*tasks)
        for port in self.ports:
            port.send_bpdu(self.get_bpdu(port.id).serialize())
        end = datetime.datetime.now()
        print(f"Sent BPDUS, took {(end - start).total_seconds()}s", flush=True)
        self.last_bpdu_sent = datetime.datetime.now()

    # sends a message to a particular port or to all ports other than the one the message is received from
    def send_message(self, data: str, port_known: bool, port_received_from: int, destination_port: int):
        for port in self.ports:
            # send only on enabled ports
            if port.is_active():
                if port_known and port.id == destination_port:
                    port.send(json.dumps(data).encode('utf-8'))
                elif not port_known and port_received_from != port.id:
                    port.send(json.dumps(data).encode('utf-8'))

    def process_message(self, message, port_received_on):
        """
        This method performs the logic to update the forwarding table and forward messages on the appropriate port(s)

        :param message: JSON message that was received
        :param port_received_on: 0-indexed port that the message was received on
        :return: None
        """
        if not self.port_id_to_portObj[port_received_on].is_active():
            print(f"Ignoring on port {port_received_on}", flush=True)
        else:
            destination = ""
            try:
                destination = message["dest"]
                source = message["source"]
                timestamp = datetime.datetime.now()
                # add source -> port id to forwarding table
                self.update_forwarding_table(port_received_on, source, timestamp)
            except (TypeError, KeyError) as e:
                print(repr(e), flush=True)
                return
            # port id of destination or None if it does not exist
            destination_port = self.get_port_to_send_message(destination)
            # if destination port does not exist in forwarding_table send to every port apart from port received from
            if destination_port < 0:
                print(f"Broadcasting {message['dest']} / {str(message['msg_id'])} to all active ports", flush=True)
                self.send_message(message, False, port_received_on, -1)
            # send to port only if destination is not the same as the port the message was received on
            elif destination_port != port_received_on:
                print(f"Forwarding {message['dest']} / {str(message['msg_id'])} to {destination_port}", flush=True)
                self.send_message(message, True, port_received_on, destination_port)
        if self.bpdu_interval_expired():
            self.send_bpdus()

    # update port of source with timestamp
    def update_forwarding_table(self, port: int, src: str, curtime: datetime.datetime):
        self.forwarding_table[src] = (port, curtime)

    # checks if forwarding table entry is still valid. If not, deletes it and returns False
    def is_valid(self, key) -> bool:
        if (datetime.datetime.now() - self.forwarding_table[key][1]).total_seconds() <= 5:
            return True
        else:
            del self.forwarding_table[key]
            return False

    # returns port if it is in forwarding table otherwise None
    def get_port_to_send_message(self, destination: str):
        if destination in self.forwarding_table and self.is_valid(destination):
            return self.forwarding_table[destination][0]
        return -1

    # cleans the last root port and sets the new root port
    def set_root_port_status(self, port_heard_on: int):
        """
        Resets the status of the last root as a designated and sets the new root status
        :param port_heard_on: 0-indexed id of new root port
        :return: None
        """
        for port in self.ports:
            if port.status == PortStatus.ROOT and port.id != port_heard_on:
                port.status = PortStatus.DESIGNATED
        self.port_id_to_portObj[port_heard_on].status = PortStatus.ROOT

    # sets port the best BPDU was received on as the root port
    def update_root_port(self, best_bpdu_received: BPDU, port_heard_on: int):
        if self.root != best_bpdu_received.root:
            self.root = best_bpdu_received.root
            print(f"New Root: {self.root}", flush=True)
        self.root_cost = best_bpdu_received.cost + 1
        self.set_root_port_status(port_heard_on)
        print(f"Root port: {port_heard_on}", flush=True)


def begin_bridge():
    """Starts bridge and listens for messages on ports"""
    print("Bridge starting up", flush=True)
    PORTS = []
    port_id_to_portObj = {}
    for i, lan_port in enumerate(args.lan_ports):
        newPort = Port(i, lan_port)
        # save port id as key with port object as value for quick lookup of object by unique id
        port_id_to_portObj[i] = newPort
        # add port to list of ports
        PORTS.append(newPort)
    sockets = list(map(lambda p: p.socket, PORTS))
    # dictionary that maps socket object to which port id it listens on
    socket_to_port = dict(map(lambda p: (p.socket, p.id), PORTS))
    bridge = Bridge(PORTS, args.bridge_id, socket_to_port, port_id_to_portObj)
    # Now we send a "hello" BPDU to all LANs to announce that we're here
    bridge.send_bpdus()

    # Main loop
    while True:
        # the subsets of the contents of the lists passed in, containing the incoming
        # data buffered and available to be read.
        readable, _, execeptable = select.select(sockets, [], sockets, 0.45)
        """
         for each the message we received,
         if its type is "bpdu", we update the spanning tree,
         if its type is "data", we update the forwarding table and send the message
         If we haven't received anything for half a second, we broadcast our BPDU
        """
        if len(readable) > 0:
            for s in readable:
                data, addr = s.recvfrom(1500)
                message = data.decode('utf-8')
                # port id that the message is received on
                port_received_on = socket_to_port[s]
                print(f"Received message: {data} on {port_received_on}", flush=True)
                try:
                    message = json.loads(message)
                    # updating the spanning tree:
                    if message["type"] == "bpdu":
                        bridge.update(message, port_received_on)
                    # updating the forwarding table and send message
                    else:
                        bridge.process_message(message, port_received_on)
                except (TypeError, KeyError) as e:
                    print(repr(e), flush=True)
        else:
            bridge.send_bpdus()


def begin_with_profiling():
    """Function to run program with profiling stats for bridge"""
    with cProfile.Profile() as p:
        begin_bridge()
    print("profiling done")
    stats = pstats.Stats(p)
    stats.sort_stats(pstats.SortKey.TIME)
    stats.print_stats()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='CS 3700 bridge')
    parser.add_argument('bridge_id', type=str, help="Bridge ID (e.g., 02ab)")
    parser.add_argument('lan_ports', metavar='lan_port', type=int, nargs='+', help="UDP ports to connect to LANs")
    args = parser.parse_args()
    # call begin_with_profiling instead to get profiling stats
    begin_bridge()
