#!/usr/bin/env -S python3 -u

import argparse, socket, time, json, select, struct, sys, math
from typing import Dict
from sender_window import SenderWindow

DATA_SIZE = 1375
MAX_WINDOW_SIZE = 4


def log(message):
    sys.stderr.write(message + "\n")
    sys.stderr.flush()


class Sender:
    tcp_buffer: SenderWindow

    def __init__(self, host, port):
        self.host = host
        self.remote_port = int(port)
        log("Sender starting up using port %s" % self.remote_port)
        self.socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.socket.bind(('0.0.0.0', 0))
        self.waiting = False
        self.tcp_buffer = SenderWindow(MAX_WINDOW_SIZE)
        self.all_data_sent = False

    def send(self, message):
        self.socket.sendto(json.dumps(message).encode('utf-8'), (self.host, self.remote_port))

    def run(self):
        while True:
            sockets = [self.socket, sys.stdin] if not self.waiting else [self.socket]
            socks = select.select(sockets, [], [], 0.1)[0]
            for conn in socks:
                if conn == self.socket:
                    k, addr = conn.recvfrom(65535)
                    try:
                        msg = json.loads(k.decode('utf-8'))
                    except ValueError:
                        log("Invalid json received")
                        continue
                    log("Received message '%s'" % msg)
                    self.tcp_buffer.set_ack_no(msg["header"]["sno"])
                    self.waiting = False
                    self.send_data()

                    if self.all_data_sent:
                        self.try_to_exit()
                elif conn == sys.stdin:
                    data = sys.stdin.read(DATA_SIZE)
                    if len(data) == 0:
                        self.all_data_sent = True
                        self.try_to_exit()
                        continue
                    self.send_data(data)

    def try_to_exit(self):
        if self.tcp_buffer.all_data_acked():
            log("All done!")
            sys.exit(0)

    def send_data(self, data: str = "") -> None:
        if data:
            self.tcp_buffer.add_data(data)
        data_to_send = self.tcp_buffer.get_data_to_send()
        if not data_to_send:
            self.waiting = True
            return

        for seq_no, data in data_to_send:
            msg = {"header": {"sno": seq_no}, "body": {"type": "msg", "data": data}}
            log("Sending message '%s'" % msg)
            self.send(msg)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='send data')
    parser.add_argument('host', type=str, help="Remote host to connect to")
    parser.add_argument('port', type=int, help="UDP port number to connect to")
    args = parser.parse_args()
    sender = Sender(args.host, args.port)
    sender.run()
